import datetime as dt
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import JSON, Column, DateTime, Float, Integer, String
from sqlalchemy.orm import Mapped, declared_attr, mapped_column, relationship

from mirix.constants import MAX_EMBEDDING_DIM
from mirix.orm.custom_columns import CommonVector, EmbeddingConfigColumn
from mirix.orm.mixins import OrganizationMixin, UserMixin
from mirix.orm.sqlalchemy_base import SqlalchemyBase
from mirix.settings import settings

if TYPE_CHECKING:
    from mirix.orm.organization import Organization
    from mirix.orm.user import User


class Insight(SqlalchemyBase, OrganizationMixin, UserMixin):
    """
    洞察 - AI生成的可执行建议

    An Insight is an actionable recommendation generated by AI based on
    patterns, anomalies, and analysis of the user's work data.

    Insight Categories:
        - efficiency: 效率优化建议
        - time_management: 时间管理建议
        - health: 健康和工作生活平衡建议
        - skill_development: 技能发展建议
        - project_management: 项目管理建议

    Attributes:
        id: Unique ID for this insight
        category: Insight category (efficiency, time_management, health, etc.)
        title: Insight title
        content: Detailed insight content with context and reasoning
        action_items: List of specific actionable steps
        priority: Priority level (1-10)
        impact_score: Estimated impact if acted upon (0-10)
        related_patterns: List of pattern IDs that led to this insight
        status: Current status (new, acknowledged, in_progress, applied, dismissed)
        generated_at: When this insight was generated
        metadata_: Additional metadata (affected_projects, estimated_time, etc.)
    """

    __tablename__ = "insight"

    # Primary key
    id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        doc="Unique ID for this insight",
    )

    # Insight classification
    category: Mapped[str] = mapped_column(
        String,
        nullable=False,
        doc="洞察类别 / Insight category: efficiency, time_management, health, skill_development, project_management",
    )

    # Basic info
    title: Mapped[str] = mapped_column(
        String,
        nullable=False,
        doc="洞察标题 / Insight title",
    )

    content: Mapped[str] = mapped_column(
        String,
        nullable=False,
        doc="洞察详细内容 / Detailed insight content with context, reasoning, and benefits",
    )

    # Actionable steps
    action_items: Mapped[list] = mapped_column(
        JSON,
        default=list,
        nullable=False,
        doc="行动项列表 / List of specific actionable steps the user can take",
    )

    # Scoring
    priority: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=5,
        doc="优先级 (1-10) / Priority level, 1=lowest, 10=highest",
    )

    impact_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="预估影响分数 (0-10) / Estimated impact score if this insight is acted upon",
    )

    # Pattern relationships
    related_patterns: Mapped[list] = mapped_column(
        JSON,
        default=list,
        nullable=False,
        doc="相关模式ID列表 / List of pattern IDs that led to this insight",
    )

    # Status tracking
    status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="new",
        doc="状态 / Current status: new, acknowledged, in_progress, applied, dismissed",
    )

    # Time tracking
    generated_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        doc="生成时间 / When this insight was generated by AI",
    )

    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        doc="用户确认时间 / When the user acknowledged this insight",
    )

    applied_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        doc="应用时间 / When the user marked this insight as applied",
    )

    # Additional metadata
    metadata_: Mapped[dict] = mapped_column(
        JSON,
        default=dict,
        nullable=True,
        doc="其他元数据 / Additional metadata (affected_projects, estimated_time, related_goals, etc.)",
    )

    # Last modification tracking
    last_modify: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=lambda: {
            "timestamp": datetime.now(dt.timezone.utc).isoformat(),
            "operation": "created",
        },
        doc="Last modification info including timestamp and operation type",
    )

    # Created timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(dt.timezone.utc),
        nullable=False,
        doc="Timestamp when this insight was created",
    )

    embedding_config: Mapped[Optional[dict]] = mapped_column(
        EmbeddingConfigColumn, nullable=True, doc="Embedding configuration"
    )

    # Vector embedding field based on database type
    if settings.mirix_pg_uri_no_default:
        from pgvector.sqlalchemy import Vector

        content_embedding = mapped_column(
            Vector(MAX_EMBEDDING_DIM),
            nullable=True,
            doc="Vector embedding of insight content for semantic search",
        )
    else:
        content_embedding = Column(
            CommonVector,
            nullable=True,
            doc="Vector embedding of insight content for semantic search",
        )

    @declared_attr
    def organization(cls) -> Mapped["Organization"]:
        """
        Relationship to the Organization that owns this insight.
        """
        return relationship(
            "Organization", back_populates="insights", lazy="selectin"
        )

    @declared_attr
    def user(cls) -> Mapped["User"]:
        """
        Relationship to the User that owns this insight.
        """
        return relationship("User", lazy="selectin")
