import datetime as dt
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import JSON, Column, DateTime, Float, Integer, String
from sqlalchemy.orm import Mapped, declared_attr, mapped_column, relationship

from mirix.orm.mixins import OrganizationMixin, UserMixin
from mirix.orm.sqlalchemy_base import SqlalchemyBase

if TYPE_CHECKING:
    from mirix.orm.organization import Organization
    from mirix.orm.user import User


class WorkSession(SqlalchemyBase, OrganizationMixin, UserMixin):
    """
    工作会话 - 记录一段连续的工作时间段

    A WorkSession represents a continuous period of focused work activity.
    It is automatically generated by analyzing raw_memory data to identify
    continuous work periods on specific projects or activities.

    Attributes:
        id: Unique ID for this work session
        start_time: When the work session started
        end_time: When the work session ended
        duration: Duration in seconds
        project_id: Associated project ID (can be null for unclassified sessions)
        activity_type: Type of activity (e.g., "coding", "meeting", "research", "writing")
        focus_score: AI-calculated focus score (0-10), based on context switches, etc.
        app_breakdown: JSON object with time spent in each app (e.g., {"VSCode": 3600, "Chrome": 1800})
        metadata_: Additional metadata (URLs visited, files edited, etc.)
        raw_memory_references: List of raw_memory IDs that constitute this session
    """

    __tablename__ = "work_session"

    # Primary key
    id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        doc="Unique ID for this work session",
    )

    # Time range
    start_time: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        doc="工作会话开始时间 / When the work session started",
    )

    end_time: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        doc="工作会话结束时间 / When the work session ended",
    )

    duration: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="会话持续时间（秒） / Duration of the session in seconds",
    )

    # Project association
    project_id: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
        doc="关联的项目ID / Associated project ID (nullable for unclassified work)",
    )

    # Activity classification
    activity_type: Mapped[str] = mapped_column(
        String,
        nullable=False,
        doc="活动类型 / Activity type: coding, meeting, research, writing, design, etc.",
    )

    # AI-calculated metrics
    focus_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=5.0,
        doc="专注度评分 (0-10) / Focus score calculated by AI based on context switches",
    )

    # App usage breakdown
    app_breakdown: Mapped[dict] = mapped_column(
        JSON,
        default=dict,
        nullable=False,
        doc="各应用使用时间统计 / Time spent in each app, e.g., {'VSCode': 3600, 'Chrome': 1800}",
    )

    # Additional metadata
    metadata_: Mapped[dict] = mapped_column(
        JSON,
        default=dict,
        nullable=True,
        doc="其他元数据 / Additional metadata (URLs visited, files edited, tasks completed, etc.)",
    )

    # Last modification tracking
    last_modify: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=lambda: {
            "timestamp": datetime.now(dt.timezone.utc).isoformat(),
            "operation": "created",
        },
        doc="Last modification info including timestamp and operation type",
    )

    # Created timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(dt.timezone.utc),
        nullable=False,
        doc="Timestamp when this work session was created",
    )

    # References to raw memory items
    raw_memory_references: Mapped[list] = mapped_column(
        JSON,
        default=list,
        nullable=False,
        doc="引用的原始记忆ID列表 / List of raw_memory IDs that constitute this session",
    )

    @declared_attr
    def organization(cls) -> Mapped["Organization"]:
        """
        Relationship to the Organization that owns this work session.
        """
        return relationship(
            "Organization", back_populates="work_sessions", lazy="selectin"
        )

    @declared_attr
    def user(cls) -> Mapped["User"]:
        """
        Relationship to the User that owns this work session.
        """
        return relationship("User", lazy="selectin")
